export const NEW_PROJECT_FORM = 'NEW_PROJECT_FORM';
export const GET_PROJECTS = 'GET_PROJECTS';
export const ADD_PROJECT = 'ADD_PROJECT';
export const CURRENT_PROJECT = "CURRENT_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";